/** Presentation tuning is isolated from the lifecycle classes for balancing and tests. */
export const exitPresentationConfig = Object.freeze({
  visual: Object.freeze({
    thickness: 0.05,
    surfaceOffset: 0.14,
    minimumLightResponse: 0.08,
    reducedMinimumLightResponse: 0.12,
    maximumLightResponse: 0.16,
    baseEmissiveStrength: 0.12,
    maximumEmissiveStrength: 0.42,
    proximityRange: 7.5,
    glitchStripCount: 16,
    maximumGlitchOffset: 0.22,
    reducedGlitchScale: 0.55,
    transitionScaleX: 0.05,
    transitionScaleY: 0.016,
  }),
  trigger: Object.freeze({
    activationDistance: 0.58,
    rearTolerance: 0.28,
    edgeInset: 0.24,
    verticalTolerance: 0.18,
    minimumApproachSeconds: 0.12,
    minimumApproachSpeed: 0.24,
    minimumFacingAlignment: 0.22,
    maximumDeltaSeconds: 0.1,
    invalidApproachDecay: 2.25,
  }),
  transition: Object.freeze({
    totalSeconds: 0.82,
    inputReductionSeconds: 0.22,
    distortionPeakSeconds: 0.3,
    fadeStartSeconds: 0.26,
    fadeEndSeconds: 0.76,
  }),
  audio: Object.freeze({
    humFrequencyHz: 101.4,
    electricalFrequencyHz: 1_267,
    transitionFrequencyHz: 67,
    humGain: 0.052,
    electricalGain: 0.014,
    outputGain: 0.13,
    refDistance: 1.4,
    maxDistance: 23,
    rolloffFactor: 1.22,
    phaseDelaySeconds: 0.0037,
    farPhaseCancellation: 0.025,
    nearPhaseCancellation: 0.17,
    parameterRampSeconds: 0.045,
    activationRampSeconds: 0.35,
    cutSeconds: 0.055,
    transitionToneSeconds: 0.22,
    reducedModulationScale: 0.48,
  }),
});
